// export const lspList = [
//     {
//       id: 1,
//       value: 'Advocates',
//       label: 'Advocates',
//     },
//     {
//       id: 2,
//       value: 'Arbitrators',
//       label: 'Arbitrators',
//     },
//     {
//       id: 3,
//       value: 'Mediators',
//       label: ' Mediators',
//     },
//     {
//       id: 4,
//       value: 'Notaries',
//       label: 'Notaries',
//     },
//     {
//       id: 5,
//       value: 'Document Writers',
//       label: 'Document Writers',
//     },
//   ];
  
//   export const ratingList = [
//     {
//       id: 1,
//       value: '1',
//       label: '1🌟',
//     },
//     {
//       id: 2,
//       value: '2',
//       label: '2🌟',
//     },
//     {
//       id: 3,
//       value: '3',
//       label: '3🌟',
//     },
//     {
//       id: 4,
//       value: '4',
//       label: '4🌟',
//     },
//     {
//       id: 5,
//       value: '5',
//       label: '5🌟',
//     },
//   ];
  
  export const dataList = [
    {
      id: 1,
      title: 'Samanraj',
      serviceTime: '45-60min',
      deliveryFee: 3.44,
      // category: 'place',
      cuisine: 'american',
      price: 2500,
      coverSrc: '/images/places/ameri.jpg',
     

     coverSrc1: ' /images/lawyers_prof/img2.jpg',
        name: 'Samanraj ',
        type_of_lsp: 'Freelancer',
        lang: 'English, Hindi, Tamil',
        exp: '12',
        rating: 5,
        location: 'Dharavi',
        district: 'Mumbai',
        phone: '+91 9876543210',
        skills: 'Carpenter'
    },
    {
      id: 2,
      title: 'Ram Gupta',
      serviceTime: '15-20min',
      deliveryFee: 4.94,
      // category: 'place',
      cuisine: 'italian',
      rating: 4,
      price: 1000,
      coverSrc: '/images/places/italian.webp',

      coverSrc1: '/images/lawyers_prof/img3.jpg',
      name: 'Ram Gupta',
      type_of_lsp: 'Freelancer',
      lang: 'English, Gujarati, Marathi',
      exp: '8',
      location: 'Ghatkopar',
      district: 'Mumbai',
      phone: '+91 8765432109',
      skills: 'Plumber'
},

    {
      id: 3,
      title: 'Munna Shukla',
      serviceTime: '30-22min',
      deliveryFee: 4.94,
      // category: 'place',
      cuisine: 'chinese',
      rating: 3,
      price: 2000,
      coverSrc: '/images/places/china.jpg',
 

      coverSrc1: ' /images/lawyers_prof/img1.jpg',
      name: 'Munna Shukla',
      type_of_lsp: 'Contract Worker',
      lang: 'English, Hindi, Kannada',
      exp: '15',
      location: 'Kanjurmarg',
      district: 'Mumbai',
      phone: '+91 7654321098',
      skills: 'Painter'
    },
    {
      id: 4,
      title: 'Dhiraj Jaiswar',
      serviceTime: '10-18min',
      deliveryFee: 2.14,
      // category: 'place',
      cuisine: 'american',
      rating: 1,
      price: 1800,
      coverSrc: '/images/places/sea.jpg',
      coverSrc1: '/images/lawyers_prof/img4.jpg',
      name: 'Dhiraj Jaiswar',
      type_of_lsp: 'Freelancer',
      lang: 'English, Marathi, Punjabi',
      exp: '7',
      location: 'Vidyavihar',
      district: 'Mumbai',
      phone: '+91 6543210987',
      skills: 'Electrician'
    },
    {
      id: 5,
      title: 'Anand raj',
      serviceTime: '25-30min',
      deliveryFee: 6.79,
      // category: 'place',
      cuisine: 'italian',
      rating: 5,
      price: 2000,
      coverSrc: '/images/places/italiian.jpg',
      coverSrc1: '/images/lawyers_prof/img5.jpg',
      name: 'Anand raj',
      type_of_lsp: 'Daily Labour',
      lang: 'English, Hindi, Telugu',
      exp: '9',
      location: 'Kalyan',
      district: 'Thane',
      phone: '+91 5432109876',
      skills: 'Plasterer'
    },
    {
      id: 6,
      title: 'Mohan Shah',
      serviceTime: '5-15min',
      deliveryFee: 2.87,
      // category: 'place',
      cuisine: 'chinese',
      rating: 5,
      price: 3500,
      coverSrc: '/images/places/fookyew2.jpg',
      coverSrc1: '/images/lawyers_prof/img6.jpg',
      name: 'Mohan Shah',
      type_of_lsp: 'Daily Labour',
      lang: 'English, Marathi, Gujarati',
      exp: '11',
      location: 'Wadala',
      district: 'Mumbai',
      phone: '+91 4321098765',
      skills: 'Mason'
    },
    {
      id: 7,
      title: 'Prashant Bose',
      serviceTime: '50-65min',
      deliveryFee: 8.5,
      // category: 'dish',
      cuisine: 'american',
      rating: 2,
      price: 2200,
      coverSrc: '/images/dishes/nacho-burger.jpg',
      coverSrc1: '/images/lawyers_prof/img7.jpg',
      name: 'Prashant Bose',
      type_of_lsp: 'Daily Labour',
      lang: 'English, Hindi, Bengali',
      exp: '14',
      location: 'Dombivali',
      district: 'Thane',
      phone: '+91 3210987654',
      skills:'Mason'
    },
    {
      id: 8,
      title: 'Rahul Prasad',
      serviceTime: '10-15min',
      deliveryFee: 1.8,
      // category: 'dish',
      cuisine: 'italian',
      rating: 1,
      price: 1900,
      coverSrc: '/images/dishes/Mushroom-Risotto-Recipe-1-1200.jpg',
      coverSrc1: '/images/lawyers_prof/img8.jpg',
      name: 'Rahul Prasad',
      type_of_lsp: 'FreeLancer',
      lang: 'English, Marathi, Kannada',
      exp: '6',
      location: 'GTB Nagar',
      district: 'Mumbai',
      phone: '+91 2109876543',
      skills: 'Electrician'
    },
    {
      id: 9,
      title: 'Maninder Singh Sodhi',
      serviceTime: '12-18min',
      deliveryFee: 3.33,
      // category: 'dish',
      cuisine: 'chinese',
      rating: 4,
      price: 2750,
      coverSrc: '/images/dishes/shiitake-salmon-fried-rice-0218-103230720.jpg',
      coverSrc1: '/images/lawyers_prof/img9.jpg',
      name: 'Maninder Singh Sodhi',
      type_of_lsp: 'Daily Labour',
      lang: 'English, Hindi, Punjabi',
      exp: '10',
      location: 'Kandivali',
      district: 'Mumbai',
      phone: '+91 1098765432',
      skills: 'Plasterer'
    },
    {
      id: 10,
      title: 'Jatin Arjun',
      serviceTime: '30-38min',
      deliveryFee: 1.9,
      // category: 'dish',
      cuisine: 'american',
      rating: 2,
      price: 4350,
      coverSrc: '/images/dishes/pesto-chicken.jpg',
      coverSrc1: '/images/lawyers_prof/img10.jpg',
      name: 'Jatin Arjun',
      type_of_lsp: 'Freelancer',
      lang: 'English, Hindi, Telugu',
      exp: '7',
      location: 'Govandi',
      district: 'Mumbai',
      phone: '+91 7654321098',
      skills: 'Painter'
    },
    {
      id: 11,
      title: 'Chandrakant',
      serviceTime: '16-20min',
      deliveryFee: 4.1,
      // category: 'dish',
      cuisine: 'italian',
      rating: 3,
      price: 3300,
      coverSrc: '/images/dishes/as-tomato-bruschetta-articleLarge.jpg',


      coverSrc1: '/images/lawyers_prof/img11.jpg',
      name: 'Chandrakant Iyer',
      type_of_lsp: 'Freelancer',
      lang: 'English, Hindi, Tamil',
      exp: '8',
      location: 'Sanpada',
      district: 'Mumbai',
      phone: '+91 0987654321',
      skills: 'Plumber'

    },
    {
      id: 12,
      title: 'Pratik',
      serviceTime: '24-30min',
      deliveryFee: 1.5,
      // category: 'dish',
      cuisine: 'chinese',
      rating: 2,
      price: 4100,
      coverSrc: '/images/dishes/dimsums.jpg',
      coverSrc1: '/images/lawyers_prof/img12.jpg',
      name: 'Pratik bengali',
      type_of_lsp: 'Contract Worker',
      lang: 'English, Marathi, Bengali',
      exp: '13',
      location: 'sion',
      district: 'Mumbai',
      phone: '+91 8765432101',
      skills: 'Carpenter'
    },
  ];
  